/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 rook.glb --transform --types
Files: rook.glb [1.88MB] > rook-transformed.glb [105.02KB] (94%)
*/
import React from 'react'
import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useSpring, animated } from '@react-spring/three'
import { type PieceProps } from '../type'

type GLTFResult = GLTF & {
    nodes: {
        rook3: THREE.Mesh
    }
    materials: {
        ['Material.001']: THREE.MeshStandardMaterial
    }
}

export const WhiteRook: React.FC<PieceProps> = (props) => {
    const { nodes, materials } = useGLTF(
        '/White/rook-transformed.glb'
    ) as GLTFResult
    const animationProps = useSpring({
        position: props.position,
        config: { duration: 1000 }, // Animation duration in milliseconds
    })

    return (
        <animated.group
            {...animationProps}
            dispose={null}
            rotation={[0, Math.PI, 0]}
            onClick={props.onClick}
        >
            <mesh
                geometry={nodes.rook3.geometry}
                material={materials['Material.001']}
            />
        </animated.group>
    )
}

useGLTF.preload('/White/rook-transformed.glb')
